// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/cue-sh/unity

package unity

// Manifest defines the schema of the manifest that a project must define to be
// added to the unity test setup
#Manifest: {
	// Versions is a list of CUE versions that are known good to the project. That
	// is to say, running unity test -project with the list of versions should
	// result in success
	Versions: [...string] @go(,[]string)
}
